#pragma once

#include <cstdint>

struct Block
{
    enum Type : std::uint16_t
    {
        Air,
        Dirt,
        GrassBlock,
        Stone,
        Grass,
        Sand,
        SandRuby,
        SandStone,
        WoodPlank,
        StoneBricks,
        Clay,
        WoodLog,
        Leaves,
        CopperOre,
        IronOre,
        GoldOre,
        CopperBlock,
        IronBlock,
        GoldBlock,
        Bricks,
        Snow,
        Ice,
        RubyBlock,
        WoodenPlatform,
        Workbench,
        Glass,
        Furnace,
        Painting,
        Sapling,
        SnowBlueRuby,
        BlueRubyBlock,
        Door,
        Jar,
        WoodenTable,
        WoodenWardrobe,
        WoodenBookshelf,
        IceBricks,
        IceTable,
        IceWardrobe,
        IceBookshelf,
        IcePlatform,
        SandTable,
        SandWardrobe,
        SandBookshelf,
        SandPlatform,
        WoodenChest,
        IceChest,
        SandChest,
        BoneChest,
        BoneBricks,
        BoneTable,
        BoneWardrobe,
        BoneBookshelf,
        BonePlatform,
        Count,
    };

    Block::Type type = Block::Air;
};
